### ISSUE TITLE
New Feature Delete by URL

### ISSUE THREAD

**Issue by YTKacperSKY** [juliarn/PasteServer#26]
Adding a feature for deleting the paste just by a url would be nice. 
so for example ShareX can show you a deletion URL to delete your paste like:
https://example.org/documents/delete/$key$/$secret$ or something similar

**Comment by juliarn** [comment]
Sounds good, I can look into this. :)

**Comment by juliarn** [comment]
Changed the protocol in 2757b5913ea4008a7410eee905f74a25b012b22a
Deletion is now done by opening a URL in exact the format you mentioned above :)
